const fs = require('fs');
const path = require('path');

const filePath = path.resolve(__dirname, '../backend/data/typescript_curriculum.json');
const data = JSON.parse(fs.readFileSync(filePath, 'utf-8'));

const section6 = data.topics[5];
if (!section6 || !section6.name.includes("Section 6")) {
    console.error("Section 6 not found at index 5");
    process.exit(1);
}

section6.subtopics = [
  {
    "id": "ts_classes_01",
    "title": "Create Classes, Fields & Instances",
    "image": "/assets/typescript/ts_classes/01-class-blueprints.png",
    "content": "# Create Classes, Fields & Instances\n\n## 1. What is a Class?\nThink of a class as a reusable blueprint for creating objects. Instead of manually writing out `{ name: 'Max', age: 36 }` over and over, you create a `User` class. \n\nIn TypeScript, unlike plain JavaScript, you **must explicitly declare your instance fields** before you use them in the constructor. If you try to assign `this.name = ...` without declaring `name` first, TypeScript will throw a helpful error!\n\n```ts\nclass User {\n  // 💡 Explicitly declaring fields that every instance will have\n  name: string;\n  age: number;\n\n  constructor(n: string, a: number) {\n    // ✅ OK: These assignments work because we declared the fields above\n    this.name = n;\n    this.age = a;\n  }\n}\n```\n\n## 2. Instantiating Objects\nWhen you use the `new` keyword, you allocate a separate, brand-new object in memory and run the constructor function to initialize its data.\n\n```ts\n// 💡 The 'new' keyword builds a distinct object using our blueprint\nconst max = new User('Max', 36);\nconst fred = new User('Fred', 29);\n```\n*Note: Constructor parameter names (like `n` and `a`) are just local implementation details. They don't have to match the class field names (`name` and `age`).*\n\n## 3. What Happens During Compilation?\nWhen TypeScript compiles this class into JavaScript, all the type annotations (like `: string` and `: number`) completely disappear. However, the class structure and the constructor assignments remain, because classes are natively supported in modern JavaScript!\n\n## Complete Code Snippet\n```ts\nclass User {\n  // 💡 Instance fields must be declared up front\n  name: string;\n  age: number;\n\n  constructor(displayName: string, yearsOld: number) {\n    // ✅ OK: Initializing the instance fields\n    this.name = displayName;\n    this.age = yearsOld;\n  }\n\n  // 💡 A method available on all instances\n  describe(): string {\n    return this.name + ' is ' + this.age + ' years old.';\n  }\n}\n\nconst max = new User('Max', 36);\nconst fred = new User('Fred', 29);\n\nconsole.log(max.describe());\nconsole.log(fred.describe());\n```",
    "questions": [
      {
        "type": "mcq",
        "question": "You write a constructor that assigns `this.name = n`. Why does TypeScript require you to declare the `name` field at the top of the class first?",
        "options": [
          "It establishes the exact shape of the instance, ensuring that every `User` object generated by this class possesses a strictly typed `name` field.",
          "It tells Node.js to create a database column for that property.",
          "It automatically makes the class abstract.",
          "It hides the field from being visible at runtime."
        ],
        "correct": 0,
        "explanation": "TypeScript needs to know the \"shape\" of your blueprint before it allows you to assign values to it. Declaring the fields up front guarantees the object's structure."
      },
      {
        "type": "mcq",
        "question": "What exactly happens under the hood when you execute `new User('Max', 36)`?",
        "options": [
          "It allocates a brand new object in memory linked to the class blueprint, and immediately invokes the constructor to initialize it.",
          "It creates a TypeScript type alias that disappears during compilation.",
          "It triggers the compiler to rebuild the entire project.",
          "It merges two interfaces together into a single object."
        ],
        "correct": 0,
        "explanation": "The `new` operator is a core JavaScript feature that instantiates a fresh object and runs the class's setup function (the constructor)."
      }
    ]
  },
  {
    "id": "ts_classes_02",
    "title": "Use Parameter Properties & Access Modifiers",
    "image": "/assets/typescript/ts_classes/02-parameter-properties.png",
    "content": "# Use Parameter Properties & Access Modifiers\n\n## 1. Access Modifiers (`public` and `private`)\nIn a large application, you don't want outside code randomly altering an object's internal state. TypeScript introduces **Access Modifiers** to protect your data:\n* `public`: (Default) The field can be read and modified from anywhere.\n* `private`: The field can ONLY be read or modified from *inside* the class where it was defined.\n\n```ts\nclass User {\n  public name: string;\n  private age: number; // 💡 Protected from outside access!\n\n  constructor(n: string, a: number) {\n    this.name = n;\n    this.age = a;\n  }\n}\n```\n\n## 2. Parameter Properties Shortcut\nWriting out field declarations, constructor parameters, and `this.field = param` assignments is incredibly repetitive. TypeScript offers a brilliant shortcut: **Parameter Properties**.\n\nIf you place an access modifier (like `public` or `private`) directly in front of a constructor parameter, TypeScript automatically creates the field and assigns it for you!\n\n```ts\nclass User {\n  // 💡 This one line automatically creates the 'name' and 'age' fields AND assigns them!\n  constructor(public name: string, private age: number) {}\n}\n```\n*Note: If you omit the modifier in the constructor, it remains just a normal function parameter and does not become a class field.*\n\n## 3. Development vs. Runtime\nRemember, `private` and `public` are TypeScript features. They prevent you from making mistakes while writing code, but they are completely removed when compiled to JavaScript. (Modern JavaScript does have native `#privateFields`, but that is a different feature!).\n\n## Complete Code Snippet\n```ts\nclass User {\n  // 💡 A normal public field initialized directly\n  public hobbies: string[] = [];\n\n  // ✅ OK: Parameter properties automatically declare and assign 'name' and 'age'\n  constructor(public name: string, private age: number) {}\n\n  addHobby(hobby: string): void {\n    this.hobbies.push(hobby);\n  }\n\n  greet(): string {\n    return 'Hi, I am ' + this.name + ' and I am ' + this.age + '.';\n  }\n}\n\nconst user = new User('Max', 36);\n\n// ✅ OK: 'name' is public\nuser.name = 'Maximilian'; \nuser.addHobby('TypeScript');\n\n// ❌ Error: Property 'age' is private and only accessible within class 'User'.\n// console.log(user.age); \n\nconsole.log(user.greet(), user.hobbies);\n```",
    "questions": [
      {
        "type": "mcq",
        "question": "What is the specific trigger that tells TypeScript to turn a constructor parameter into an automatic instance field?",
        "options": [
          "Prefixing the parameter with an access modifier such as `public` or `private`.",
          "Including a `return` statement in the constructor.",
          "Using the `new` keyword when calling the constructor.",
          "Making the parameter optional with a question mark (`?`)."
        ],
        "correct": 0,
        "explanation": "Adding an access modifier inside the constructor parameters activates the Parameter Properties shorthand, automatically declaring and assigning the field."
      },
      {
        "type": "mcq",
        "question": "You declare a field as `private age: number;`. Where in your codebase is it legal to read or modify this field?",
        "options": [
          "Only from methods located inside the exact declaring class.",
          "From anywhere in the module where the class is exported.",
          "From any subclass that extends the declaring class.",
          "Only from within an interface."
        ],
        "correct": 0,
        "explanation": "The `private` modifier is strictly limited to the class in which the field is defined, preventing any outside code (even subclasses) from tampering with it."
      }
    ]
  },
  {
    "id": "ts_classes_03",
    "title": "Protect State with readonly, Accessors & Static Members",
    "image": "/assets/typescript/ts_classes/03-readonly-accessors-static.png",
    "content": "# Protect State with readonly, Accessors & Static Members\n\n## 1. The `readonly` Modifier\nSometimes `private` isn't what you want; you want a field to be public so anyone can read it, but you never want it to be reassigned after it's initialized. That's where `readonly` comes in!\n\n```ts\nclass User {\n  readonly id: string = 'USER-1';\n}\nconst u = new User();\n// ❌ Error: Cannot assign to 'id' because it is a read-only property.\n// u.id = 'USER-2';\n```\n*Warning: `readonly` is shallow! If you mark an array as readonly, you cannot point it to a new array, but you CAN still push items into the existing array!*\n\n## 2. Getters & Setters (Accessors)\nSometimes you need to run logic when a property is read or changed (like validating a name). Getters and Setters allow you to write functions that *look and act* like normal properties from the outside.\n\n```ts\nclass User {\n  private _firstName = '';\n\n  // 💡 Setter: Validates the data before saving it\n  set firstName(name: string) {\n    if (name.trim() === '') throw new Error('Invalid name.');\n    this._firstName = name;\n  }\n\n  // 💡 Getter: Computes data on the fly when requested\n  get firstName() { return this._firstName; }\n}\n// ✅ OK: Accessed like a normal property, not a function call!\nuser.firstName = 'Max'; \n```\n\n## 3. Static Members\nMost properties belong to an *instance* of a class (`new User()`). But what if you want a property or utility function attached to the class blueprint itself? You use the `static` keyword.\n\n```ts\nclass User {\n  static readonly entityType = 'USER_MODEL';\n  static describeModel() { return 'A user in our system'; }\n}\n// ✅ OK: Called directly on the class itself!\nconsole.log(User.entityType);\n```\n\n## Complete Code Snippet\n```ts\nclass User {\n  // 💡 Static members are attached directly to the class\n  static readonly entityId = 'USER';\n  \n  // 💡 Readonly prevents reassignment, but allows array mutations\n  readonly hobbies: string[] = [];\n  \n  // 💡 Private backing fields for our accessors\n  private _firstName = '';\n  private _lastName = '';\n\n  set firstName(name: string) {\n    if (name.trim() === '') throw new Error('Invalid first name.');\n    this._firstName = name;\n  }\n\n  set lastName(name: string) {\n    if (name.trim() === '') throw new Error('Invalid last name.');\n    this._lastName = name;\n  }\n\n  get fullName(): string {\n    return this._firstName + ' ' + this._lastName;\n  }\n\n  static greet(): string {\n    return 'Hello from the User type.';\n  }\n}\n\nconst max = new User();\n// 💡 These look like property assignments, but they actually trigger the 'set' methods!\nmax.firstName = 'Max';\nmax.lastName = 'Schwarz';\nmax.hobbies.push('Coding'); // ✅ OK: Readonly arrays can still be mutated\n\n// 💡 Calling static members directly on the class\nconsole.log(User.entityId, User.greet());\nconsole.log(max.fullName, max.hobbies);\n```",
    "questions": [
      {
        "type": "mcq",
        "question": "You have a field defined as `readonly hobbies: string[] = [];`. Why does TypeScript allow you to successfully run `user.hobbies.push('Coding')`?",
        "options": [
          "Because `readonly` only protects the property binding (preventing you from reassigning it to a completely different array). It does not freeze the internal contents of the mutable array.",
          "Because the `.push()` method creates a brand new class under the hood.",
          "Because arrays completely ignore TypeScript rules.",
          "Because the member was implicitly marked as `static`."
        ],
        "correct": 0,
        "explanation": "The `readonly` modifier in TypeScript is shallow. It prevents variable reassignment, but deep mutations (like pushing to an array or changing a nested object's properties) are still permitted."
      },
      {
        "type": "mcq",
        "question": "If you define a getter method inside a class using `get fullName(): string { ... }`, how must you access it on an instance named `user`?",
        "options": [
          "By accessing it like a standard property: `user.fullName`",
          "By executing it like a standard function: `user.fullName()`",
          "By calling it statically on the class: `User.fullName`",
          "By using the new keyword: `new fullName()`"
        ],
        "correct": 0,
        "explanation": "Getters (and setters) expose computed logic through standard property syntax. You do not use parentheses to execute them."
      }
    ]
  },
  {
    "id": "ts_classes_04",
    "title": "Build Inheritance with super & protected",
    "image": "/assets/typescript/ts_classes/04-inheritance-protected.png",
    "content": "# Build Inheritance with super & protected\n\n## 1. The `extends` Keyword\nOften, multiple classes share the exact same logic. Instead of duplicating code, you can use **Inheritance**. The `extends` keyword allows a new subclass to inherit all accessible fields and methods from a base class.\n\n```ts\nclass Employee extends User {\n  // Employee inherits everything from User, and can add its own specific logic!\n}\n```\n\n## 2. Using `super()`\nIf your subclass has its own `constructor`, you are strictly required to call `super()` before using `this`. \n\nCalling `super(...)` executes the base class's constructor. You must pass it any arguments that the base class requires to initialize its portion of the object.\n\n```ts\nclass Employee extends User {\n  constructor(name: string, public jobTitle: string) {\n    // 💡 Passes 'name' up to the User constructor to handle\n    super(name);\n  }\n}\n```\n\n## 3. The `protected` Modifier\nEarlier, we learned about `public` and `private`. But what if a base class has data that it wants to share with its subclasses, but hide from the rest of the world? \n\nEnter `protected`. A protected member is invisible to outside code, but perfectly accessible to any class that `extends` it.\n\n## Complete Code Snippet\n```ts\nclass User {\n  constructor(\n    public name: string,\n    // 💡 Protected: Hidden from the outside, but visible to Employee!\n    protected readonly internalId: string,\n  ) {}\n\n  describe(): string {\n    return this.name + ' [' + this.internalId + ']';\n  }\n}\n\nclass Employee extends User {\n  constructor(name: string, id: string, public jobTitle: string) {\n    // ✅ OK: We must execute the base constructor first!\n    super(name, id);\n  }\n\n  work(): string {\n    // ✅ OK: We can access 'this.internalId' because it is protected, not private.\n    return this.name + ' works as ' + this.jobTitle +\n      ' with internal id ' + this.internalId;\n  }\n}\n\nconst employee = new Employee('Max', 'EMP-01', 'Developer');\nconsole.log(employee.describe());\nconsole.log(employee.work());\n\n// ❌ Error: Property 'internalId' is protected and only accessible within class 'User' and its subclasses.\n// console.log(employee.internalId); \n```",
    "questions": [
      {
        "type": "mcq",
        "question": "If a subclass (`Employee`) declares its own constructor, why does TypeScript strictly require you to call `super()` inside of it?",
        "options": [
          "Because the base class (`User`) must initialize its portion of the inherited instance before the subclass is allowed to modify the object using `this`.",
          "Because calling `super()` automatically makes all inherited fields public.",
          "Because interfaces cannot be compiled without it.",
          "Because `super()` creates a static utility method."
        ],
        "correct": 0,
        "explanation": "When inheriting, the base class's setup logic must run first to ensure the object is properly constructed before the subclass applies its specific changes."
      },
      {
        "type": "mcq",
        "question": "When designing a base class, what is the specific advantage of making a field `protected` instead of `private`?",
        "options": [
          "It keeps the field hidden from external callers, while still allowing derived subclasses to access and collaborate with it.",
          "It makes the field visible to all callers globally.",
          "It forces the field to be utilized inside an interface.",
          "It restricts the field to static methods only."
        ],
        "correct": 0,
        "explanation": "The `protected` modifier serves as a middle ground: it hides data from public use, but permits trusted, inheriting subclasses to read or modify it."
      }
    ]
  },
  {
    "id": "ts_classes_05",
    "title": "Design Abstract Base Classes",
    "image": "/assets/typescript/ts_classes/05-abstract-classes.png",
    "content": "# Design Abstract Base Classes\n\n## 1. What is an Abstract Class?\nSometimes, you want to create a base class that shares common logic, but you **never** want anyone to instantiate it directly. For example, a generic `UIElement` shouldn't be created on its own; it should only exist as a base for a `Button` or a `Dropdown`.\n\nBy adding the `abstract` keyword to a class, you create a blueprint that *cannot be constructed directly*. It only exists to be extended by concrete subclasses.\n\n```ts\nabstract class UIElement {\n  constructor(public identifier: string) {}\n}\n\n// ❌ Error: Cannot create an instance of an abstract class.\n// const el = new UIElement('base'); \n```\n\n## 2. Abstract Methods\nAbstract classes become incredibly powerful when you add **abstract methods**. An abstract method dictates the name and return type of a function, but provides *no implementation body*. \n\nIt forces any subclass that extends it to write their own specific implementation of that method!\n\n```ts\nabstract class UIElement {\n  // 💡 Forces subclasses to provide their own specific 'open' logic!\n  abstract open(): string; \n}\n```\n\n*Note: Just like types and interfaces, abstract classes are a TypeScript-only feature. The `abstract` keywords are stripped away when compiled to JavaScript.*\n\n## Complete Code Snippet\n```ts\nabstract class UIElement {\n  constructor(public identifier: string) {}\n\n  // 💡 A concrete method: inherited exactly as is by all subclasses\n  clone(targetLocation: string): string {\n    return this.identifier + ' cloned into ' + targetLocation;\n  }\n\n  // 💡 An abstract method: subclasses MUST implement this themselves!\n  abstract open(): string;\n}\n\n// ✅ OK: A concrete subclass extending the abstract base\nclass SideDrawerElement extends UIElement {\n  constructor(\n    identifier: string,\n    public position: 'left' | 'right',\n  ) {\n    // 💡 Fulfilling the base class's constructor requirements\n    super(identifier);\n  }\n\n  // ✅ OK: We are strictly required to implement 'open' here\n  open(): string {\n    return this.identifier + ' opens from the ' + this.position;\n  }\n}\n\nconst drawer = new SideDrawerElement('main-drawer', 'left');\nconsole.log(drawer.open());\nconsole.log(drawer.clone('#mobile-shell'));\n\n// ❌ Error: Cannot create an instance of an abstract class.\n// const base = new UIElement('base'); \n```",
    "questions": [
      {
        "type": "mcq",
        "question": "What is the primary architectural purpose of marking a base class as `abstract`?",
        "options": [
          "To centralize shared implementation logic while strictly preventing developers from instantiating it directly, forcing them to construct a concrete subclass instead.",
          "To automatically generate JSON serialization at runtime.",
          "To completely replace the need for interfaces.",
          "To force all fields within the class to behave as static properties."
        ],
        "correct": 0,
        "explanation": "Abstract classes serve as foundational blueprints. They provide shared behavior but are intentionally incomplete, requiring a concrete subclass to fill in the missing pieces (like abstract methods) before instantiation."
      },
      {
        "type": "mcq",
        "question": "When `SideDrawerElement` extends the abstract `UIElement` class, what happens if it fails to implement an `abstract open(): string;` method defined in the base class?",
        "options": [
          "TypeScript will throw a compile-time error demanding that the concrete subclass implements all inherited abstract members.",
          "TypeScript will automatically generate an empty `open` method.",
          "The code will compile perfectly, but crash at runtime.",
          "The `SideDrawerElement` will silently convert into an interface."
        ],
        "correct": 0,
        "explanation": "Abstract methods represent a strict contract. Any concrete subclass is legally obligated to provide a full implementation for every abstract method defined by its parent."
      }
    ]
  },
  {
    "id": "ts_classes_06",
    "title": "Define & Use Interface Object Contracts",
    "image": "/assets/typescript/ts_classes/06-interface-contracts.png",
    "content": "# Define & Use Interface Object Contracts\n\n## 1. What is an Interface?\nAn `interface` is one of TypeScript's most powerful features. It describes the exact shape an object must take, without providing any actual values or logic. \n\nThink of it like a job description: it states what skills are required, but it doesn't do the actual work.\n\n```ts\ninterface Authenticatable {\n  email: string;\n  password: string;\n  \n  // 💡 A method signature: defines parameters and return types, but no implementation body!\n  login(): void;\n  logout(): void;\n}\n```\n\n## 2. Using Interfaces as Types\nOnce you define an interface, you can use it to strictly type an object. \n\nThe concrete object you create is forced to supply **every single property and method** promised by the interface. If you miss a property, misspell a key, or return the wrong type from a method, TypeScript will immediately flag an error.\n\n```ts\nlet user: Authenticatable;\n\n// ✅ OK: This object perfectly matches the interface contract\nuser = {\n  email: 'test@example.com',\n  password: 'abc1',\n  login() { /* create a session */ },\n  logout() { /* clear the session */ },\n};\n```\n\n## Complete Code Snippet\n```ts\n// 💡 The Interface: Defining the required shape and behaviors\ninterface Authenticatable {\n  email: string;\n  password: string;\n  login(): void;\n  logout(): void;\n}\n\n// ✅ OK: The Object: Providing the actual data and logic\nconst user: Authenticatable = {\n  email: 'test@example.com',\n  password: 'abc1',\n  \n  login() {\n    console.log('Session created for ' + this.email);\n  },\n  \n  logout() {\n    console.log('Session cleared for ' + this.email);\n  },\n};\n\nuser.login();\nuser.logout();\n```",
    "questions": [
      {
        "type": "mcq",
        "question": "When defining a method inside an interface (e.g., `login(): void;`), what information must you provide?",
        "options": [
          "Only the method's signature (its parameter types and return type), without providing any implementation body.",
          "The complete logic linking it to a database.",
          "A constructor implementation.",
          "The generated JavaScript output."
        ],
        "correct": 0,
        "explanation": "Interfaces exist purely to describe behavior contracts. They dictate what a method must look like, but they never dictate how the method actually performs its job."
      },
      {
        "type": "mcq",
        "question": "If you annotate an object variable with an interface (e.g., `let user: Authenticatable`), what is strictly required of that object?",
        "options": [
          "It must supply an implementation or value for every single property and method required by the interface.",
          "It only needs to provide one of the listed properties.",
          "It can only contain static members.",
          "It is forbidden from holding any runtime values."
        ],
        "correct": 0,
        "explanation": "TypeScript uses structural typing. If an object claims to satisfy an interface, it must physically possess every single piece of data and behavior that the interface demands."
      }
    ]
  },
  {
    "id": "ts_classes_07",
    "title": "Compare Interfaces, Type Aliases & Callable Contracts",
    "image": "/assets/typescript/ts_classes/07-interfaces-aliases.png",
    "content": "# Compare Interfaces, Type Aliases & Callable Contracts\n\n## 1. Interfaces vs. Type Aliases\nBoth `type` aliases and `interface` declarations can describe the shape of an object. So which should you use?\n* **Type Aliases** are highly flexible. They can describe objects, but they can also describe unions (`type ID = string | number`) and primitives.\n* **Interfaces** specialize entirely in object shapes and classes. \n\n## 2. Declaration Merging (Interfaces Only!)\nA unique feature of Interfaces is **Declaration Merging**. If you declare two interfaces with the exact same name, TypeScript will automatically merge them into a single, combined contract!\n\n```ts\ninterface Session { token: string; }\ninterface Session { expiresAt: Date; }\n\n// ✅ OK: The Session object must now have BOTH token and expiresAt!\nconst session: Session = {\n  token: 'abc',\n  expiresAt: new Date(),\n};\n```\n*Warning: Type aliases do not support this. If you try to declare two types with the same name, you will get a compiler error.*\n\n## 3. Callable Contracts\nBoth Types and Interfaces can describe the shape of a function (a \"callable contract\"). However, function `type` aliases are generally cleaner and much more common in modern codebases.\n\n```ts\n// 💡 Cleaner: Function Type Alias\ntype SumFn = (a: number, b: number) => number;\n\n// 💡 Clunkier: Interface representing a function\ninterface SumInterface { (a: number, b: number): number; }\n```\n\n## Complete Code Snippet\n```ts\n// 💡 Demonstration of Interface Declaration Merging\ninterface Session {\n  token: string;\n}\n\ninterface Session {\n  expiresAt: Date;\n}\n\n// 💡 Function typed with an Alias\ntype SumFn = (a: number, b: number) => number;\n\n// 💡 Function typed with an Interface\ninterface SumInterface {\n  (a: number, b: number): number;\n}\n\n// ✅ OK: The object satisfies the merged interface requirements\nconst session: Session = {\n  token: 'abc',\n  expiresAt: new Date(Date.now() + 60_000),\n};\n\nconst sumWithAlias: SumFn = (a, b) => a + b;\nconst sumWithInterface: SumInterface = (a, b) => a + b;\n\nconsole.log(session.token, sumWithAlias(2, 3), sumWithInterface(4, 5));\n```",
    "questions": [
      {
        "type": "mcq",
        "question": "What is \"Declaration Merging\" in the context of TypeScript interfaces?",
        "options": [
          "A feature where TypeScript automatically combines multiple interface declarations sharing the exact same name into one unified contract.",
          "A tool that concatenates multiple JavaScript files into a single bundle.",
          "A process that runs both constructors simultaneously.",
          "A command that converts an interface directly into a class."
        ],
        "correct": 0,
        "explanation": "Declaration merging is unique to interfaces. It allows libraries and developers to augment existing interface contracts by declaring them again with additional properties."
      },
      {
        "type": "mcq",
        "question": "If you need to describe the signature of a standalone callback function, which syntax is more commonly preferred and easier to read?",
        "options": [
          "A function type alias (e.g., `type Callback = () => void;`).",
          "An abstract class with a static execution method.",
          "A namespace containing an anonymous function.",
          "A private class constructor."
        ],
        "correct": 0,
        "explanation": "While interfaces can technically model callable signatures, function type aliases are significantly cleaner and are the standard convention for typing functions in modern TypeScript."
      }
    ]
  },
  {
    "id": "ts_classes_08",
    "title": "Implement Interfaces & Depend on Minimum Shapes",
    "image": "/assets/typescript/ts_classes/08-implements-minimum.png",
    "content": "# Implement Interfaces & Depend on Minimum Shapes\n\n## 1. The `implements` Keyword\nInterfaces are exceptionally powerful when combined with classes. By using the `implements` keyword, you ask TypeScript to strictly verify that your class fulfills the contract promised by the interface.\n\n```ts\n// 💡 This class is forced to include 'email', 'password', 'login()', and 'logout()'\nclass AuthenticatableUser implements Authenticatable {\n  // Implementation goes here...\n}\n```\n\nYou can even implement multiple interfaces by separating them with commas (e.g., `implements Authenticatable, Logger`). \n\n*Note: An interface establishes a **minimum requirement**. Your class is completely free to add extra fields or methods that the interface didn't ask for.*\n\n## 2. Depending on Abstractions\nWhy go through this trouble? Because it allows you to decouple your functions from specific classes! \n\nIf a function requires an argument to be of type `Authenticatable`, it doesn't care if you pass it an `AuthenticatableUser`, an `AdminUser`, or a plain object. As long as the object has the minimum required shape, the function accepts it. This makes your code highly flexible and incredibly easy to test.\n\n## Complete Code Snippet\n```ts\ninterface Authenticatable {\n  email: string;\n  password: string;\n  login(): void;\n  logout(): void;\n}\n\n// ✅ OK: Class fulfills all requirements of the Authenticatable interface\nclass AuthenticatableUser implements Authenticatable {\n  // 💡 Adding 'userName' which is an extra, non-required field!\n  constructor(\n    public userName: string,\n    public email: string,\n    public password: string,\n  ) {}\n\n  login(): void {\n    console.log(this.userName + ' logged in.');\n  }\n\n  logout(): void {\n    console.log(this.userName + ' logged out.');\n  }\n}\n\n// 💡 This function depends on the INTERFACE, not the specific CLASS\nfunction authenticate(user: Authenticatable): void {\n  user.login();\n}\n\nconst max = new AuthenticatableUser('Max', 'max@example.com', 'secret');\n\n// ✅ OK: 'max' fulfills the Authenticatable shape, so it is accepted!\nauthenticate(max);\nmax.logout();\n```",
    "questions": [
      {
        "type": "mcq",
        "question": "If a class `implements` an interface, is it allowed to include additional properties and methods that are not listed in the interface?",
        "options": [
          "Yes, `implements` enforces a minimum structural shape, but it does not forbid the class from adding additional, specific behaviors.",
          "No, the class must perfectly mirror the interface with no additions.",
          "Yes, but the extra members must be marked as `private`.",
          "Yes, but it is limited to exactly one extra method."
        ],
        "correct": 0,
        "explanation": "An interface establishes a baseline contract. As long as the class fulfills all the minimum requirements of that contract, it is free to extend itself with extra capabilities."
      },
      {
        "type": "mcq",
        "question": "In the `authenticate` function, why is it considered a best practice to type the parameter as `(user: Authenticatable)` instead of `(user: AuthenticatableUser)`?",
        "options": [
          "It accepts any object or instance that fulfills the required interface capabilities, decoupling the function from a specific rigid class implementation.",
          "It permanently disables type checking for that parameter.",
          "It transforms the `login` method into a static function.",
          "It emits the interface into the compiled JavaScript runtime."
        ],
        "correct": 0,
        "explanation": "Depending on an abstraction (the interface) rather than a concrete implementation (the class) makes your functions much more flexible and easier to supply with mock data during testing."
      }
    ]
  },
  {
    "id": "ts_classes_09",
    "title": "Extend Interfaces & Understand Type Erasure",
    "image": "/assets/typescript/ts_classes/09-extend-erase.png",
    "content": "# Extend Interfaces & Understand Type Erasure\n\n## 1. Extending Interfaces\nJust like classes can inherit from other classes using `extends`, an Interface can inherit from other Interfaces! \n\nThis creates a brand new, highly specific contract that combines the requirements of the base interface with new, specific requirements. This is completely different from \"Declaration Merging\" (which alters the original interface).\n\n```ts\n// 💡 Inherits everything from Authenticatable, and adds a 'role'\ninterface AuthenticatableAdmin extends Authenticatable {\n  role: 'admin' | 'super-admin';\n}\n```\nAn interface can even extend multiple interfaces simultaneously (e.g., `extends Authenticatable, HasPermissions`).\n\n## 2. The Illusion of TypeScript (Type Erasure)\nAs you build complex architectures with interfaces, `implements`, and `extends`, it is absolutely vital to remember **Type Erasure**.\n\nJavaScript has no native concept of an \"Interface\". Therefore, when you compile your code using `tsc`, **every single interface disappears completely**.\n\nInterfaces exist solely to improve your development-time experience by catching errors in your editor. They are **not** runtime validators. If you fetch JSON from a database and assign it to an `AuthenticatableAdmin` interface, TypeScript will happily assume it's true, but there are zero runtime protections guaranteeing the data is actually shaped correctly!\n\n## Complete Code Snippet\n```ts\ninterface Authenticatable {\n  email: string;\n  login(): void;\n}\n\ninterface HasPermissions {\n  permissions: string[];\n}\n\n// 💡 This interface requires the traits of both bases, plus its own 'role'\ninterface AuthenticatableAdmin extends Authenticatable, HasPermissions {\n  role: 'admin' | 'super-admin';\n}\n\nconst admin: AuthenticatableAdmin = {\n  email: 'admin@example.com',\n  role: 'admin',\n  permissions: ['courses:write'],\n  login() {\n    console.log(this.email + ' logged in as ' + this.role);\n  },\n};\n\nadmin.login();\nconsole.log(admin.permissions);\n\n// 💡 If you compile this file, you'll see the 'admin' object, but ALL interfaces will be erased!\n```",
    "questions": [
      {
        "type": "mcq",
        "question": "How does using the `extends` keyword on an interface differ from \"Declaration Merging\"?",
        "options": [
          "`extends` creates a brand new derived interface incorporating the base requirements, while Declaration Merging silently alters the original interface.",
          "`extends` rewrites and deletes the original interface entirely.",
          "`extends` emits runtime validation checks into the JavaScript.",
          "There is no difference; they are exactly the same concept."
        ],
        "correct": 0,
        "explanation": "Extending an interface generates a new contract for specialized use cases, leaving the base contract clean and untouched. Merging actively changes the base contract."
      },
      {
        "type": "mcq",
        "question": "When you compile your TypeScript code into JavaScript, what happens to your `interface` declarations and the `implements` keywords on your classes?",
        "options": [
          "They are completely erased. JavaScript has no native concept of interfaces, so they exist only at compile-time for developer tooling.",
          "They are transformed into JavaScript Classes.",
          "They are converted into runtime JSON schemas for data validation.",
          "They are hoisted and executed before the main application logic."
        ],
        "correct": 0,
        "explanation": "TypeScript is fundamentally a compile-time tool. All advanced typing constructs (like interfaces and generics) are erased from the final emitted JavaScript."
      }
    ]
  }
];

fs.writeFileSync(filePath, JSON.stringify(data, null, 2));
console.log("Section 6 patched successfully!");
